spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seckmsfb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: fkp123456
mybatis-plus:
  mapper-locations:
    - classpath:mappers/*.xml
mybatis:
  databaseType: mysql
logging:
  level:
    root: debug
