spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name:  org.postgresql.Driver
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: org.sqlite.JDBC
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:D:\IDEAWorkSpace\mybatisplus_test\mybatisplus_demos\h2\seckmsfb;AUTO_SERVER=TRUE
#      url: jdbc:h2:mem:seckmsfb
      url: jdbc:postgresql://10.0.101.11:5432/fkp_test6?currentSchema=ccsp_storage
      validation-query: SELECT 1
#      url: jdbc:mysql://localhost:3306/seckmsfb_kms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      url: jdbc:sqlite:sqlite/seckmsfb.db?date_string_format=yyyy-MM-dd HH:mm:ss
#      username: root
#      password: SWXA1234@DAR_Mysql
      username: ccsp1
      password: swxa@1234
      filters: stat
      filter:
        wall:
          enabled: true
          config:
            strict-syntax-check: false   #关闭sql语法检查

  sql:
    init:
      schema-locations: classpath*:sql/seckmsfb_h2_DDL.sql #项目启动执行sql文件，对应DDL
      #data-locations: classpath*:sql/seckmsfb_h2_DML.sql #项目启动执行sql文件，对应DML
      mode: embedded  #初始化模式，默认EMBEDDED仅初始化嵌入式数据库,对于h2数据库需采用内存模式
mybatis-plus:
  mapper-locations:
    - classpath:mappers/*.xml
  type-handlers-package: com.fkp.type_handler
mybatis:
  databaseType: mysql
logging:
  level:
    root: debug
