spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: org.sqlite.JDBC
      driver-class-name: org.postgresql.Driver
#      url: jdbc:mysql://localhost:3306/seckmsfb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
#      url: jdbc:sqlite:sqlite/seckmsfb.db
      url: jdbc:postgresql://192.168.200.200/postgres
      username: postgres
      password: fkp123456
mybatis-plus:
  mapper-locations:
    - classpath:mappers/*.xml
mybatis:
  databaseType: postgresql
logging:
  level:
    root: info
